#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &

nitrogen --restore &
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &

sleep 0.01
~/.config/bspwm/scripts/handle-monitors.sh &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#5f819d"
bspc config normal_border_color "#282a2e"

