#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
feh --bg-fill ~/Pictures/Wallpaper/demon-slayer.jpg $

$HOME/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 20

bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"
